### ISSUE TITLE
Did you forget to upload 1.0.26-pre4?

### ISSUE THREAD

**Issue by AuroraDysis** [thomasgalliker/CrossPlatformLibrary.Settings#1]
In 1.0.26-pre3 uap10.0 target miss a library "CrossPlatformLibrary.Settings.dll"

**Comment by thomasgalliker** [comment]
can you check if it works with 1.0.26-pre5?

**Comment by AuroraDysis** [comment]
Works well, and I have a suggestion: add a Reset method to SettingsProperty.

**Comment by AuroraDysis** [comment]
I make a mistake, Netfx also miss in the nuspec

**Comment by thomasgalliker** [comment]
You're right. I gonna fix that by the next chance. Thanks for reporting.

**Comment by thomasgalliker** [comment]
1.0.27 should now contain the net45 assemblies. By the way: There is a refactoring to version 2.0 ongoing. Just open an issue if anything behaves strangly.
